import type { Metadata } from "next";

import "./globals.css";
import Header from "./components/layout/header";
import Footer from "./components/layout/footer";

// const bricolageGrotesque = Bricolage_Grotesque({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Resume",
  description: "Generated by Getnextjs Templates",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Header />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
